### ISSUE TITLE
mobx_codegen cannot generate async action

### ISSUE THREAD

**Issue by taliptako** [mobxjs/mobx.dart#144]
With the mobx_gen version 0.1.1 i'm getting error below

```
[SEVERE] mobx_codegen|mobx_generator on lib/home_store.dart (cached):
Could not make class "HomeStore" observable. Changes needed:
  1. Remove async modifier from the method "fetch"
```

My action 
```
 @action
  Future<void> fetch() async {
    var version = await lookUpVersion();
    print(version);
  }

  Future<String> lookUpVersion() async => '1.0.0';
```

**Comment by pavanpodila** [comment]
Hi @taliptako, I tried reproducing it in my own Store and it generated correctly. This is using `mobx_codegen` **0.1.1**. Can you check again?

This was in my Store class:

```dart
  @action
  Future<void> fetch() async {
    var version = await lookUpVersion();
    print(version);
  }

  Future<String> lookUpVersion() async => '1.0.0';
```


This was the generated output (relevant):

```dart
  final _$fetchAsyncAction = AsyncAction('fetch');

  @override
  Future<void> fetch() {
    return _$fetchAsyncAction.run(() => super.fetch());
  }


```

**Comment by taliptako** [comment]
How can I delete the cached assets in mobx_codegen package?
Cause when I create new flutter project I'm not getting that error too. But the previous project that I had this error still getting this error when I ran the command.

**Comment by pavanpodila** [comment]
try this: https://mobx.pub/guides/output#starting-a-clean-build

**Comment by taliptako** [comment]
Interestingly I still get the same error after running the clean command.
I zipped the project files can you test with this
[https://send.firefox.com/download/5d7f3093b5fb6525/#t1KoiRJiIv8MS0AqZwG32Q](https://send.firefox.com/download/5d7f3093b5fb6525/#t1KoiRJiIv8MS0AqZwG32Q)

**Comment by pavanpodila** [comment]
Ok, figured out the problem. It was your SDK version, which was set to **2.1.0**. It should have been **2.1.0-dev**.

I changed your pubspec.yaml to the following. Notice the following here:

- Changed the SDK version to **2.1.0-dev**
- Removed the version against **build_runner**. This gets the latest as the version used by **mobx_codegen** is also the latest. It was failing for you because the versions of `mobx`, `mobx_codegen` were old. This happened due to the older SDK version.

```yaml
name: uniquote_test
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0-dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  mobx:
  flutter_mobx:

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  mobx_codegen:


flutter:
  uses-material-design: true

```

With these changes, the `build_runner` is successfully generating the outputs.

```
[INFO] Succeeded after 995ms with 2 outputs (3 actions)

```
