### ISSUE TITLE
Error running form example

### ISSUE THREAD

**Issue by Feelthewind** [mobxjs/mobx.dart#153]
[SEVERE] mobx_codegen:mobx_generator on lib/form/form_store.dart (cached):
Could not make class "FormStore" observable. Changes needed:
  1. Remove async modifier from the method "validateUsername"

I changed the SDK version to 2.1.0-dev, but it still doesn't work.
Do i have to separate async code from actions?
I don't know why the example code doens't work.

**Comment by pavanpodila** [comment]
Try deleting the `.packages` and the `pubspec.lock` file and run the `flutter packages get` command again.

**Comment by huangyanxiong01** [comment]
Try to specify the version number for mobx, It work well
```
dependencies:
  mobx: ^0.1.3
  validators: ^2.0.0 # change to latest version
  flutter_mobx: ^0.1.1
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  build_runner: ^1.2.5
  mobx_codegen: ^0.1.2
  flutter_test
    sdk: flutter

```
