### ISSUE TITLE
Logging state changes

### ISSUE THREAD

**Issue by Bryanx** [mobxjs/mobx.dart#475]
Hi thanks for this amazing library :)

I would like to log all state changes, similar to [redux-logger](https://github.com/LogRocket/redux-logger) behavior. I am now writing these, but it's messy and tedious:
```dart
  @observable
  Page currentPage = Page.Plants;

  @action
  void setCurrentPage(value) {
    final prevState = currentPage;
    currentPage = value;
    log.d("prev state: $prevState\n"
          "action: setCurrentPage($value)\n"
          "next state $currentPage");
  }
```

Are there any solutions?

**Comment by pavanpodila** [comment]
Yes, we do but you will have to point to master branch for now. There is new feature called "spy" that allows you to do just what you described. Take a look at https://github.com/mobxjs/mobx.dart/blob/master/mobx_examples/lib/main.dart for the example of using a `spy`.

Docs for that are still pending (#467)

**Comment by Bryanx** [comment]
Thanks, I will take a look. This is looking promising :)

**Comment by DJafari** [comment]
@pavanpodila how can use spy before publish and writing docs ?

i tried :

```yml
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  mobx:
    git:
      url: https://github.com/mobxjs/mobx.dart
      path: mobx
      ref: master
  flutter_mobx:
    git:
      url: https://github.com/mobxjs/mobx.dart
      path: flutter_mobx
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.8.1
  mobx_codegen:
    git:
      url: https://github.com/mobxjs/mobx.dart
      path: mobx_codegen
      ref: master
```

but when `pub get`, i get this error :

```
Because every version of mobx_codegen from git depends on mobx from hosted and shift depends on mobx from git, mobx_codegen from git is forbidden.

So, because shift depends on mobx_codegen from git, version solving failed.
```
