### ISSUE TITLE
Missing "part '*.g.dart';".

### ISSUE THREAD

**Issue by pacifire** [mobxjs/mobx.dart#562]
```
[WARNING] mobx_codegen:mobx_generator on lib/Login/OTP/store/resendOTPStore.dart:
Missing "part 'resendOTPStore.g.dart';".
```

is the error which i am facing when i hit the command `flutter packages pub run build_runner build`

resendOTPStore.dart is as follows:

```
import 'dart:async';
import 'package:mobx/mobx.dart';

part 'resendotpstore.g.dart';

class Resendotpstore = _Resendotpstore with _$Resendotpstore;

abstract class _Resendotpstore with Store {
  @observable
  String timeleftText;
  @observable
  int resendOtpRemainingTime =
      0; //This variable will actually be manipulated...

  final int _totalTimeLeft =
      30; //This is the total time taken to resend the OTP....

//Below function will start counting to resend the OTP....
  @action
  void startCounter() {
    timeleftText =
        "Resend OTP in 00:$_totalTimeLeft seconds"; //to resend OTP we need atleast 5 seconds....

    resendOtpRemainingTime = _totalTimeLeft;
    const oneSec = const Duration(seconds: 1);

    Timer.periodic(oneSec, (timer) {
      if (resendOtpRemainingTime < 1) {
        timer.cancel();
      } else if (resendOtpRemainingTime == 1) {
        resendOtpRemainingTime = resendOtpRemainingTime - 1;
        timeleftText = "Resend OTP in 00:0$resendOtpRemainingTime second";
      } else {
        resendOtpRemainingTime = resendOtpRemainingTime - 1;
        if (resendOtpRemainingTime.toString().trim().length > 1)
          timeleftText = "Resend OTP in 00:$resendOtpRemainingTime seconds";
        else if (resendOtpRemainingTime.toString().trim().length == 1)
          timeleftText = "Resend OTP in 00:0$resendOtpRemainingTime seconds";
      }
    });
  } //startCounter closes here....

} //resend_otp_store closes here....

```

Dependencies used in project:
```
dependencies:
  flutter:
    sdk: flutter
   

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  firebase_messaging: 6.0.16
  photo_view: ^0.4.2
  cupertino_icons: ^0.1.2
  http: ^0.12.0
  shared_preferences: "^0.4.3"
  flutter_webview_plugin: ^0.3.11
  webview_flutter: ^0.3.5+3
  datetime_picker_formfield: 1.0.0
  package_info: ^0.4.0+3
  launch_review: ^1.0.1
  url_launcher: ^3.0.3
  smooth_star_rating: ^1.0.3
  flutter_staggered_grid_view: "^0.2.7"
  share: 0.6.1+1

  #For OTP Text field....
  pin_input_text_field: 3.0.3

  #To check whether device is connected to Internet or not....
  connectivity: 0.4.3+2

  #To capture the image from Gallery / Camera....
  image_picker: ^0.6.5+2

  #To Compress the Image....
  flutter_image_compress: ^0.6.3

  #Adding State Management to this project....
  mobx: ^1.2.1+2
  flutter_mobx: 1.1.0
  provider: 4.1.2
  json_annotation:


  


  
  
   


dev_dependencies:
  flutter_test:
    sdk: flutter
  
  #Adding State Management to this project....
  build_runner: 1.10.1
  mobx_codegen: ^1.1.0+1
  json_serializable:
  analyzer: ^0.39.2+1
```

flutter doctor output is as follows:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.1, on Mac OS X 10.15.3 19D76, locale en-IN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.48.2)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

Please guide me, what's it that i am doing wrong.
