### ISSUE TITLE
Only run mobx code generator on changed files to speed up, instead of running on every file

### ISSUE THREAD

**Issue by fzyzcjy** [mobxjs/mobx.dart#753]
Currently I am observing that, when one file is changed, it seems that mobx codegen runs on every file. This makes the codegen very slow (minutes of time). 

In https://github.com/dart-lang/build/issues/3248, it is said that:

> build_runner does only run on changed files (and files that depend on those files). Slow builds are usually the result of builders which require full analysis running on every file in the project.

Thus maybe mobx.dart can avoid full analysis when single file changes?

**Comment by pavanpodila** [comment]
Happy to take a PR if you can pick it up. My bandwidth is constrained right now.

**Comment by ezze** [comment]
Hi, guys!

If I understand it properly this happens even on changes in ANY file of the project that depends (implicitly or explicitly) on at least one MobX store. Right?

We faced the issue that each time we change anything (even add an empty line to a widget) in our files we get a full rebuild of the project (the time of incremental build is equal to the time of initial build). So we're insterested in optimizing rebuild times.

@pavanpodila As I can see [here](https://github.com/mobxjs/mobx.dart/blob/9c4eb1dbd99228cbc11425b59472f6142b3816fd/mobx_codegen/lib/src/mobx_codegen_base.dart) is a custom implementation of `Generator` but since I'm relatively new to Flutter not sure where to start yet. Any reference to start guide would be useful.

**Comment by ezze** [comment]
Although it might be not related to this issue but I found it useful to [configure](https://pub.dev/packages/build_config) `build_runner` with `build.yaml` file located in the root of the project:

```yaml
targets:
  $default:
    builders:
      mobx_codegen|mobx_generator:
        enabled: true
        generate_for:
          include:
            - lib/**/stores/*.dart
      auto_route_generator|autoRouteGenerator:
        enabled: true
        generate_for:
          include:
            - lib/services/navigation/magnum_app_router.dart
```

In my case the most time to build/rebuild was taken by [auto_route](https://pub.dev/packages/auto_route). Narrowing down files triggering the rebuild by `genereate_for` decreased rebuild duration up to 10 times.
