### ISSUE TITLE
Each and every mobx store will warn: `Avoid using private types in public APIs.` with default linters in Flutter 3.0

### ISSUE THREAD

**Issue by fzyzcjy** [mobxjs/mobx.dart#809]
Documentation of that lint: https://dart-lang.github.io/linter/lints/library_private_types_in_public_api.html

What do you think? Shall we let users to manually suppress this lint for each and every store? That sounds very verbose.

**Comment by jfahrenkrug** [comment]
A workaround is to use `class SomeStore extends _SomeStoreBase with _$SomeStore {}` instead of `class SomeStore = _SomeStoreBase with _$SomeStore;`. However, the next linting error then occurs in the `.g.dart` file because a leading underscore is used for a local identifier (`no_leading_underscores_for_local_identifiers`). So it seems that some code changes to MobX might be needed to satisfy these new linter rules.

**Comment by fzyzcjy** [comment]
Good idea!

> However, the next linting error then occurs in the .g.dart

No worries: We can configure build runner to add `//ignore_for_file` for .g.dart

**Comment by muhammedaydogan** [comment]
> No worries: We can configure build runner to add //ignore_for_file for .g.dart

How do you do that? Did you read it from a document or sth?

**Comment by hugobrancowb** [comment]
you can put the following code in the  `build.yaml`

```yaml
targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          preamble: |
            // ignore_for_file: ...
```
