### ISSUE TITLE
Unable to use MultiReactionBuilder

### ISSUE THREAD

**Issue by Maryusz** [mobxjs/mobx.dart#938]
Hello all, 
I'm trying to use the new MultiReactionBuilder to refactor an app I've build, even if in the pubspec i specified:
`mobx: ^2.2.0
  flutter_mobx: ^2.1.0`

And I'm able to access all the parts of the standard flutter_mobx library (like Observer, ReactionBuilder), this new one, doesn't show. 

I'm doing something wrong? 
P.s. I'm new using mobx/flutter_mobx.

**Comment by fzyzcjy** [comment]
Hi, maybe try to `pub get`, and if it does not work, paste `pubspec.lock` to have a look

**Comment by Maryusz** [comment]
Actions done:

1. `flutter clean`
2. ` flutter pub get`

The pubspec.lock its 1259 lines long, I post the flutter_mobx / mobx lines only, but if necessary i can post the file in its totality.

```
flutter_mobx:
    dependency: "direct main"
    description:
      name: flutter_mobx
      sha256: "2aa91babd4b66a7345675f67e3733a35ec6da3f42ad86799fce5363a322944be"
      url: "https://pub.dev"
    source: hosted
    version: "2.1.0"
    
    mobx:
    dependency: "direct main"
    description:
      name: mobx
      sha256: "0afcf88b3ee9d6819890bf16c11a727fc8c62cf736fda8e5d3b9b4eace4e62ea"
      url: "https://pub.dev"
    source: hosted
    version: "2.2.0"
    
  mobx_codegen:
    dependency: "direct dev"
    description:
      name: mobx_codegen
      sha256: "52a6904b93fa1ceadc5ed4cd67e24fd05a21340d39cff0a213179fc83e179dba"
      url: "https://pub.dev"
    source: hosted
    version: "2.4.0"
```
